### PR TITLE
Create update.circle.yml

### PR DESCRIPTION
**Pull request by q83894529**
Regular update

### CODE REVIEW

**Comment by Young178** [comment]
who are you？

**Comment by q83894529** [comment]
> who are you？

a u yangbing?

**Comment by Young178** [comment]
I'm not yangbing

**Comment by Young178** [comment]
Are you an internal member of radar? Or is it not? What is the current situation with radar

**Comment by Young178** [comment]
Is this your QQ number? I added you but didn't reply

**Comment by fengbailq** [comment]
都是雷达币持有者

**Comment by fengbailq** [comment]
> > 你是谁？
> 
> 欧阳冰？

你是雷友吧

**Pull request closed without merging**
